extended_about:
  type: string
  textarea: true
  description:
    en: 'Text of the first section on the About page.'
  default: |
            <p>Welcome to our Community Forum! This is a place to socialize and share ideas.</p>
            <p>Please take a moment to make yourself familiar with our <strong><a href="/guidelines">Guidelines</a></strong>.</p>
